# Pages CMS configuration
# If your Pages CMS setup expects .pages.yml, rename this file.
media:
  input: public/uploads
  output: /uploads

content:
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: body
        label: Body
        type: rich-text
